<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="15" hostname="DESKTOP-DJ4FDME" failures="3" tests="3" name="Test(failed)" time="0.107" errors="0" timestamp="2023-10-14T06:14:25 IST">
  <testcase classname="learnTestNG.TestScenario9" name="fifth_testcase" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [Helloooo] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Helloooo] but found [Hello]
at learnTestNG.TestScenario9.fifth_testcase(TestScenario9.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="learnTestNG.TestScenario7" name="third_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [Helloooo] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Helloooo] but found [Hello]
at learnTestNG.TestScenario7.third_testcase(TestScenario7.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- third_testcase -->
  <testcase classname="learnTestNG.TestScenario4" name="first_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [Helloooo] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Helloooo] but found [Hello]
at learnTestNG.TestScenario4.first_testcase(TestScenario4.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="learnTestNG.TestScenario9" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="learnTestNG.TestScenario4" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="learnTestNG.TestScenario7" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="learnTestNG.TestScenario9" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="learnTestNG.TestScenario9" name="first_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- first_testcase -->
  <testcase classname="learnTestNG.TestScenario7" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="learnTestNG.TestScenario7" name="first_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- first_testcase -->
  <testcase classname="learnTestNG.TestScenario4" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="learnTestNG.TestScenario9" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="learnTestNG.TestScenario7" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="learnTestNG.TestScenario4" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="learnTestNG.TestScenario9" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="learnTestNG.TestScenario7" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="learnTestNG.TestScenario4" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="learnTestNG.TestScenario4" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
</testsuite> <!-- Test(failed) -->
